### ISSUE TITLE
Issue about traineddata folder 

### ISSUE THREAD

**Issue by aronsoyol** [dolugen/tesseract-mnc#1]
Thanks for your excellent work, 

there is a little issue in tess_combine script. The data folder for final traineddata should be `/usr/local/share/tessdata/` on my Mac.
 
I didn't test for other platform.

**Comment by dolugen** [comment]
Hello @aronsoyol!

At the time, the scripts were tested on an Ubuntu machine, I'm sure there would be a few differences in file paths on your Mac.

But thanks for reporting it, though!
